# Generated by Django 3.2 on 2022-03-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FirmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя фирма')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('website', models.CharField(max_length=255, verbose_name='Веб сайт')),
                ('phonenumber', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firm.usersmodel', verbose_name='Директор')),
            ],
        ),
    ]
