# Generated by Django 3.2 on 2022-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmodel',
            name='ceo',
            field=models.CharField(max_length=255, verbose_name='Директор'),
        ),
    ]
