# Generated by Django 3.2 on 2022-03-02 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_alter_firmmodel_ceo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmmodel',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='firmmodel',
            name='phone_number',
            field=models.IntegerField(default=998979142425, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона', regex='^998\\d{9}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
