# Generated by Django 3.2 on 2022-03-02 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0003_auto_20220302_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmodel',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='firmmodel',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Неверный формат веб сайта', regex='/((([A-Za-z]{3,9}:(?:\\/\\/)?)(?:[-;:&=\\+\\$,\\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\\+\\$,\\w]+@)[A-Za-z0-9.-]+)((?:\\/[\\+~%\\/.\\w-_]*)?\\??(?:[-\\+=&;%@.\\w_]*)#?(?:[\\w]*))?)/')], verbose_name='Номер телефона'),
        ),
    ]
