# Generated by Django 3.2 on 2022-03-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0005_auto_20220302_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
