# Generated by Django 3.2 on 2022-03-02 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0006_delete_usersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат Серия пасспорта', regex='[A-Z]{2}[0-9]{7}')], verbose_name='Серия и номер пасспорта')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('job', models.CharField(max_length=255, verbose_name='Позиция')),
                ('phone_number', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера телефона', regex='^998\\d{9}$')], verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firm.firmmodel')),
            ],
        ),
    ]
