# Generated by Django 3.2 on 2022-03-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm', '0008_firmmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmodel',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='firm',
            field=models.ForeignKey(db_column='firm', on_delete=django.db.models.deletion.PROTECT, to='firm.firmmodel', to_field='name'),
        ),
    ]
