# Generated by Django 3.2 on 2022-03-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0010_alter_usersmodel_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='firm',
            field=models.ForeignKey(db_column='firm', on_delete=django.db.models.deletion.PROTECT, to='firm.firmmodel', to_field='name'),
        ),
    ]
