# Generated by Django 3.2 on 2022-03-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0011_alter_usersmodel_firm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firm.firmmodel'),
        ),
    ]
