# Generated by Django 3.2 on 2022-03-02 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firm', '0013_usersmodel_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirmModel',
            new_name='CompanyModel',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='firm',
            new_name='company',
        ),
    ]
