# Generated by Django 3.2 on 2022-03-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0014_auto_20220302_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.companymodel'),
        ),
    ]
